# utils/language.py
import streamlit as st

translations = {
    'en': {
        # General
        'app_title': 'WindVision Pro',
        'app_subtitle': 'Wind Farm Management System',

        # Navigation
        'dashboard': 'Dashboard',
        'operations': 'Operations',
        'maintenance': 'Maintenance',
        'planning': 'Planning',
        'simulation': 'Simulation',
        'reports': 'Reports',
        'data_upload': 'Data Upload',
        'settings': 'Settings',
        'logout': 'Logout',

        # Login
        'login': 'Login',
        'employee_id': 'Employee ID (Example: EMP001)',
        'password': 'Password',
        'invalid_credentials': 'Invalid Employee ID or Password',

        # Dashboard
        'current_production': 'Current Production',
        'avg_efficiency': 'Average Efficiency',
        'active_turbines': 'Active Turbines',
        'wind_speed': 'Wind Speed',
        'temperature': 'Temperature',
        'humidity': 'Humidity',
        'pressure': 'Pressure',
        'wind_direction': 'Wind Direction',
        'turbine_specs': 'Turbine Specs',
        'production_trend': 'Production Trend (Last 24 Hours)',
        'hourly_power_output': 'Hourly Power Output',
        'tafila_wind_farm': 'Tafila Wind Farm',
        'live_weather': 'Live Weather',
        'last_updated': 'Last Updated',
        'developed_by': 'Developed by: Samah Mahmoud Ma\'abreh',

        # Status
        'good': 'Good',
        'warning': 'Warning',
        'issue': 'Issue',
        'failure': 'Failure',

        # Operations
        'total_power_output': 'Total Power Output',
        'current_wind_speed': 'Current Wind Speed',
        'power_curve': 'Wind Turbine Power Curve',
        'technical_specifications': 'Technical Specifications',
        'turbine_performance_ranking': 'Turbine Performance Ranking',
        'top_turbines': 'Top 10 Turbines by Total Production',
        'parameter': 'Parameter',
        'value': 'Value',
        'manufacturer': 'Manufacturer',
        'model': 'Model',
        'rated_power': 'Rated Power',
        'rotor_diameter': 'Rotor Diameter',
        'hub_height': 'Hub Height',
        'cut_in_speed': 'Cut-in Wind Speed',
        'rated_speed': 'Rated Wind Speed',
        'cut_out_speed': 'Cut-out Wind Speed',
        'max_survival': 'Max Survival Wind Speed',

        # Maintenance
        'urgent_maintenance': 'Urgent Maintenance',
        'required_maintenance': 'Required Maintenance',
        'good_condition': 'Good Condition',
        'maintenance_schedule': 'Maintenance Schedule',
        'urgent_required': 'URGENT MAINTENANCE REQUIRED - Next 24 Hours',
        'required_maintenance_text': 'REQUIRED MAINTENANCE - Within 3-7 Days',
        'immediate_inspection': 'Immediate inspection required',
        'schedule_maintenance': 'Schedule maintenance within 3 days',
        'all_good': 'All turbines are in good condition. No immediate maintenance required.',
        'turbine_efficiency_ranking': 'Turbine Efficiency Ranking',
        'maintenance_recommendations': 'Maintenance Recommendations',
        'proactive_tips': 'Proactive Maintenance Tips',
        'efficiency': 'Efficiency',
        'action': 'Action',
        'target': 'Target',

        # Planning
        'production_forecast': 'Production Forecast',
        'daily_production': 'Daily Production',
        'monthly_production': 'Monthly Production',
        'yearly_production': 'Yearly Production',
        'co2_saved_yearly': 'CO₂ Saved (Yearly)',
        'forecast_title': '7-Day Production Forecast',
        'expansion_planning': 'Expansion Planning - Add New Turbines',
        'site_selection_criteria': 'Site Selection Criteria',
        'recommended_locations': 'Recommended Locations',
        'site_comparison': 'Site Comparison',
        'best_location': 'BEST LOCATION RECOMMENDATION',
        'expected_power': 'Expected Power',
        'expected_daily': 'Expected Daily',
        'priority_score': 'Priority Score',

        # Simulation
        'simulation_controls': 'Simulation Controls',
        'select_scenario': 'Select Scenario',
        'normal_operation': 'Normal Operation',
        'turbine_failure': 'Turbine Failure',
        'wind_speed_change': 'Wind Speed Change',
        'dust_storm': 'Dust Storm',
        'add_new_turbines': 'Add New Turbines',
        'efficiency_drop': 'Efficiency Drop',
        'wind_speed_analysis': 'Wind Speed Analysis',
        'normal_speed': 'Normal Speed',
        'current_speed': 'Current Speed',
        'cut_out_speed': 'Cut-out Speed',
        'max_survival_speed': 'Max Survival',
        'simulation_results': 'Simulation Results',
        'total_production': 'Total Production',
        'production_comparison': 'Production Comparison',
        'normal_vs_simulation': 'Normal vs Simulation Production',
        'impact_analysis': 'Impact Analysis',
        'financial_impact': 'Financial Impact',
        'co2_impact': 'CO₂ Impact',
        'recommendations': 'Recommendations',

        # Reports
        'select_report_type': 'Select Report Type',
        'daily_report': 'Daily Performance Report',
        'weekly_summary': 'Weekly Summary',
        'monthly_analysis': 'Monthly Analysis',
        'turbine_health_report': 'Turbine Health Report',
        'environmental_impact': 'Environmental Impact Report',
        'total_production_metric': 'Total Production',
        'peak_production': 'Peak Production',
        'weekly_total': 'Weekly Total',
        'avg_daily': 'Average Daily Production',
        'co2_saved_weekly': 'CO₂ Saved (Weekly)',
        'co2_saved_monthly': 'CO₂ Saved (Monthly)',
        'environmental_summary': 'Environmental Impact Summary',
        'clean_energy': 'Total Clean Energy Generated',
        'co2_avoided': 'CO₂ Emissions Avoided',
        'trees_equivalent': 'Trees Equivalent',
        'oil_saved': 'Oil Saved',
        'report_preview': 'Report Preview',
        'download_report': 'Download Report',
        'select_date': 'Select Date',
        'select_month': 'Select Month',
        'select_turbine': 'Select Turbine',

        # Data Upload
        'data_management': 'Data Management',
        'upload_new_data': 'Upload New Data',
        'choose_file': 'Choose CSV file',
        'file_loaded': 'File loaded',
        'file_size': 'File size',
        'data_preview': 'Data Preview',
        'data_statistics': 'Data Statistics',
        'rows': 'Rows',
        'columns': 'Columns',
        'save_database': 'Save to Database',
        'export_all': 'Export All Data',
        'clear_all': 'Clear All Data',
        'confirm_delete': 'This will delete all data. Are you sure?',

        # Settings
        'user_settings': 'User Settings',
        'logged_in_as': 'Logged in as',
        'role': 'Role',
        'display_name': 'Display Name',
        'language_settings': 'Language',
        'select_language': 'Select Language',
        'notification_settings': 'Notification Settings',
        'email_alerts': 'Email Alerts',
        'maintenance_alerts': 'Maintenance Alerts',
        'weather_alerts': 'Weather Alerts',
        'production_alerts': 'Production Alerts',
        'threshold_settings': 'Threshold Settings',
        'efficiency_warning': 'Efficiency Warning Threshold',
        'efficiency_critical': 'Efficiency Critical Threshold',
        'wind_speed_warning': 'Wind Speed Warning',
        'wind_speed_critical': 'Wind Speed Critical',
        'display_settings': 'Display Settings',
        'theme': 'Theme',
        'chart_style': 'Chart Style',
        'refresh_interval': 'Auto-refresh Interval',
        'date_format': 'Date Format',
        'data_settings': 'Data Settings',
        'clear_cache': 'Clear Cache',
        'save_settings': 'Save Settings',

        # Common Buttons
        'save': 'Save',
        'cancel': 'Cancel',
        'refresh': 'Refresh',
        'export': 'Export',
        'upload': 'Upload',
        'delete': 'Delete',
        'confirm': 'Confirm',
        'back': 'Back',
        'next': 'Next',
        'search': 'Search',
        'filter': 'Filter',
        'download': 'Download',
        'loading': 'Loading...',
        'error': 'Error',
        'success': 'Success',

        # Time
        'hour': 'Hour',
        'day': 'Day',
        'week': 'Week',
        'month': 'Month',
        'year': 'Year',
        'power': 'Power'
    },
    'ar': {
        # General
        'app_title': 'WindVision Pro',
        'app_subtitle': 'نظام إدارة مزارع الرياح',

        # Navigation
        'dashboard': 'لوحة التحكم',
        'operations': 'التشغيل',
        'maintenance': 'الصيانة',
        'planning': 'التخطيط',
        'simulation': 'المحاكاة',
        'reports': 'التقارير',
        'data_upload': 'رفع البيانات',
        'settings': 'الإعدادات',
        'logout': 'تسجيل الخروج',

        # Login
        'login': 'تسجيل الدخول',
        'employee_id': 'الرقم الوظيفي (مثال: EMP001)',
        'password': 'الرقم السري',
        'invalid_credentials': 'الرقم الوظيفي أو الرقم السري غير صحيح',

        # Dashboard
        'current_production': 'الإنتاج الحالي',
        'avg_efficiency': 'متوسط الكفاءة',
        'active_turbines': 'التوربينات النشطة',
        'wind_speed': 'سرعة الرياح',
        'temperature': 'درجة الحرارة',
        'humidity': 'الرطوبة',
        'pressure': 'الضغط الجوي',
        'wind_direction': 'اتجاه الرياح',
        'turbine_specs': 'مواصفات التوربين',
        'production_trend': 'اتجاه الإنتاج (آخر 24 ساعة)',
        'hourly_power_output': 'الإنتاج لكل ساعة',
        'tafila_wind_farm': 'مزرعة رياح الطفيلة',
        'live_weather': 'الطقس المباشر',
        'last_updated': 'آخر تحديث',
        'developed_by': 'تم التطوير بواسطة: سماح محمود معابره',

        # Status
        'good': 'جيد',
        'warning': 'تحذير',
        'issue': 'مشكلة',
        'failure': 'عطل',

        # Operations
        'total_power_output': 'إجمالي الإنتاج',
        'current_wind_speed': 'سرعة الرياح الحالية',
        'power_curve': 'منحنى قدرة التوربين',
        'technical_specifications': 'المواصفات الفنية',
        'turbine_performance_ranking': 'ترتيب أداء التوربينات',
        'top_turbines': 'أفضل 10 توربينات من حيث الإنتاج',
        'parameter': 'الخاصية',
        'value': 'القيمة',
        'manufacturer': 'الشركة المصنعة',
        'model': 'الطراز',
        'rated_power': 'القدرة الاسمية',
        'rotor_diameter': 'قطر الدوار',
        'hub_height': 'ارتفاع البرج',
        'cut_in_speed': 'سرعة البدء',
        'rated_speed': 'سرعة القدرة الاسمية',
        'cut_out_speed': 'سرعة الإيقاف',
        'max_survival': 'أقصى سرعة للتحمل',

        # Maintenance
        'urgent_maintenance': 'صيانة عاجلة',
        'required_maintenance': 'صيانة مطلوبة',
        'good_condition': 'حالة جيدة',
        'maintenance_schedule': 'جدول الصيانة',
        'urgent_required': 'صيانة عاجلة مطلوبة - خلال 24 ساعة',
        'required_maintenance_text': 'صيانة مطلوبة - خلال 3-7 أيام',
        'immediate_inspection': 'فحص فوري مطلوب',
        'schedule_maintenance': 'جدول صيانة خلال 3 أيام',
        'all_good': 'جميع التوربينات في حالة جيدة. لا توجد صيانة فورية مطلوبة.',
        'turbine_efficiency_ranking': 'ترتيب كفاءة التوربينات',
        'maintenance_recommendations': 'توصيات الصيانة',
        'proactive_tips': 'نصائح الصيانة الاستباقية',
        'efficiency': 'الكفاءة',
        'action': 'الإجراء',
        'target': 'الهدف',

        # Planning
        'production_forecast': 'توقع الإنتاج',
        'daily_production': 'الإنتاج اليومي',
        'monthly_production': 'الإنتاج الشهري',
        'yearly_production': 'الإنتاج السنوي',
        'co2_saved_yearly': 'ثاني أكسيد الكربون الموفر (سنوياً)',
        'forecast_title': 'توقع الإنتاج للأيام السبعة القادمة',
        'expansion_planning': 'تخطيط التوسع - إضافة توربينات جديدة',
        'site_selection_criteria': 'معايير اختيار الموقع',
        'recommended_locations': 'المواقع المقترحة',
        'site_comparison': 'مقارنة المواقع',
        'best_location': 'أفضل موقع موصى به',
        'expected_power': 'القدرة المتوقعة',
        'expected_daily': 'الإنتاج اليومي المتوقع',
        'priority_score': 'درجة الأولوية',

        # Simulation
        'simulation_controls': 'إعدادات المحاكاة',
        'select_scenario': 'اختر السيناريو',
        'normal_operation': 'تشغيل عادي',
        'turbine_failure': 'عطل توربين',
        'wind_speed_change': 'تغير سرعة الرياح',
        'dust_storm': 'عاصفة ترابية',
        'add_new_turbines': 'إضافة توربينات جديدة',
        'efficiency_drop': 'انخفاض الكفاءة',
        'wind_speed_analysis': 'تحليل سرعة الرياح',
        'normal_speed': 'السرعة الطبيعية',
        'current_speed': 'السرعة الحالية',
        'cut_out_speed': 'سرعة الإيقاف',
        'max_survival_speed': 'الحد الأقصى للتحمل',
        'simulation_results': 'نتائج المحاكاة',
        'total_production': 'الإنتاج الكلي',
        'production_comparison': 'مقارنة الإنتاج',
        'normal_vs_simulation': 'الإنتاج الطبيعي مقابل المحاكاة',
        'impact_analysis': 'تحليل التأثير',
        'financial_impact': 'التأثير المالي',
        'co2_impact': 'تأثير CO₂',
        'recommendations': 'التوصيات',

        # Reports
        'select_report_type': 'اختر نوع التقرير',
        'daily_report': 'تقرير الأداء اليومي',
        'weekly_summary': 'ملخص أسبوعي',
        'monthly_analysis': 'تحليل شهري',
        'turbine_health_report': 'تقرير صحة التوربين',
        'environmental_impact': 'تقرير الأثر البيئي',
        'total_production_metric': 'إجمالي الإنتاج',
        'peak_production': 'ذروة الإنتاج',
        'weekly_total': 'الإجمالي الأسبوعي',
        'avg_daily': 'متوسط الإنتاج اليومي',
        'co2_saved_weekly': 'ثاني أكسيد الكربون الموفر (أسبوعياً)',
        'co2_saved_monthly': 'ثاني أكسيد الكربون الموفر (شهرياً)',
        'environmental_summary': 'ملخص الأثر البيئي',
        'clean_energy': 'إجمالي الطاقة النظيفة المولدة',
        'co2_avoided': 'انبعاثات CO₂ التي تم تجنبها',
        'trees_equivalent': 'ما يعادل أشجار',
        'oil_saved': 'نفط تم توفيره',
        'report_preview': 'معاينة التقرير',
        'download_report': 'تحميل التقرير',
        'select_date': 'اختر التاريخ',
        'select_month': 'اختر الشهر',
        'select_turbine': 'اختر التوربين',

        # Data Upload
        'data_management': 'إدارة البيانات',
        'upload_new_data': 'رفع بيانات جديدة',
        'choose_file': 'اختر ملف CSV',
        'file_loaded': 'تم تحميل الملف',
        'file_size': 'حجم الملف',
        'data_preview': 'معاينة البيانات',
        'data_statistics': 'إحصائيات البيانات',
        'rows': 'صفوف',
        'columns': 'أعمدة',
        'save_database': 'حفظ في قاعدة البيانات',
        'export_all': 'تصدير جميع البيانات',
        'clear_all': 'مسح جميع البيانات',
        'confirm_delete': 'سيتم حذف جميع البيانات. هل أنت متأكد؟',

        # Settings
        'user_settings': 'إعدادات المستخدم',
        'logged_in_as': 'مسجل الدخول باسم',
        'role': 'الدور',
        'display_name': 'اسم العرض',
        'language_settings': 'اللغة',
        'select_language': 'اختر اللغة',
        'notification_settings': 'إعدادات التنبيهات',
        'email_alerts': 'تنبيهات البريد الإلكتروني',
        'maintenance_alerts': 'تنبيهات الصيانة',
        'weather_alerts': 'تنبيهات الطقس',
        'production_alerts': 'تنبيهات الإنتاج',
        'threshold_settings': 'إعدادات الحدود',
        'efficiency_warning': 'حد تحذير الكفاءة',
        'efficiency_critical': 'حد الخطر للكفاءة',
        'wind_speed_warning': 'تحذير سرعة الرياح',
        'wind_speed_critical': 'خطر سرعة الرياح',
        'display_settings': 'إعدادات العرض',
        'theme': 'المظهر',
        'chart_style': 'نمط الرسم البياني',
        'refresh_interval': 'فترة التحديث التلقائي',
        'date_format': 'تنسيق التاريخ',
        'data_settings': 'إعدادات البيانات',
        'clear_cache': 'مسح الذاكرة المؤقتة',
        'save_settings': 'حفظ الإعدادات',

        # Common Buttons
        'save': 'حفظ',
        'cancel': 'إلغاء',
        'refresh': 'تحديث',
        'export': 'تصدير',
        'upload': 'رفع',
        'delete': 'حذف',
        'confirm': 'تأكيد',
        'back': 'رجوع',
        'next': 'التالي',
        'search': 'بحث',
        'filter': 'تصفية',
        'download': 'تحميل',
        'loading': 'جاري التحميل...',
        'error': 'خطأ',
        'success': 'نجاح',

        # Time
        'hour': 'ساعة',
        'day': 'يوم',
        'week': 'أسبوع',
        'month': 'شهر',
        'year': 'سنة',
        'power': 'القدرة'
    }
}


def get_text(key):
    """Get translated text based on current language"""
    if 'language' not in st.session_state:
        st.session_state['language'] = 'en'
    lang = st.session_state['language']
    return translations[lang].get(key, key)


def set_language(lang):
    """Set the application language"""
    if lang in ['en', 'ar']:
        st.session_state['language'] = lang
        return True
    return False


def get_current_language():
    """Get current language"""
    return st.session_state.get('language', 'en')